### PR TITLE
hey finally figure it out

### PR DESCRIPTION
**Pull request by C-Jalloh**
i just added some html and a little css to test it

### CODE REVIEW

**Review by SarahKapalka — APPROVED** [review]
yay great job :D

**Comment by C-Jalloh** [comment]
Hey Sarah 
What's our situation here

**Comment by SarahKapalka** [comment]
oh im sorry i am just seeing this
i'll check it out when im free

**Comment by C-Jalloh** [comment]
Join your team on Slack

Ebrima C Jallow ***@***.***) has invited you to use Slack with them, in a workspace called CTY_TECH.

Workspace name: CTY_TECH

C
Join Now [https://join.slack.com/t/ctytech/invite/enQtNDQ2NzIwNDc2NDU3OS04NjMzMTBmNDVmMWIyMGJjNTEzNjE3YzU0MTUzYjBkM2VhMzYyYzg4MmNkNzE0YWQzODFlNWRhZGQ2YjNkNWM5?x=x-p4298988802320-4260742220247-4467309410482]
Join the conversation with omarmusakeita, reply and 4 others.

Once you join, you can always access the CTY_TECH workspace at https://ctytech.slack.com/

What is Slack?

Slack is a messaging app for teams, a place you can collaborate on projects and organize conversations — so you can work together, no matter where you are.

Learn more about Slack [https://ctytech.slack.com/x-p4298988802320-4260742220247-4467309410482/?utm_medium=email&utm_source=invitation-to-join]

**Comment by SarahKapalka** [comment]
i cant join, it says the email account i use is not invited

**Comment by C-Jalloh** [comment]
Accept Ebrima C Jallow’s invitation to Slack

Ebrima C Jallow ***@***.***) has invited you to use Slack with them, in a workspace called CTY_TECH.

Workspace name: CTY_TECH

C
Join Now [https://join.slack.com/t/ctytech/invite/enQtNDQ2NzIwNDc2NDU3OS04NjMzMTBmNDVmMWIyMGJjNTEzNjE3YzU0MTUzYjBkM2VhMzYyYzg4MmNkNzE0YWQzODFlNWRhZGQ2YjNkNWM5?x=x-p4298988802320-4260742220247-4485775987377]
Join the conversation with omarmusakeita, reply and 4 others.

Once you join, you can always access the CTY_TECH workspace at https://ctytech.slack.com/

What is Slack?

Slack is a messaging app for teams, a place you can collaborate on projects and organize conversations — so you can work together, no matter where you are.

Learn more about Slack [https://ctytech.slack.com/x-p4298988802320-4260742220247-4485775987377/?utm_medium=email&utm_source=invitation-to-join]

**Comment by SarahKapalka** [comment]
[image: image.png]
look its not working, invitation is not working

**Pull request merged**
